// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package database_test

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockComputeLayer creates a new instance of MockComputeLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComputeLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComputeLayer {
	mock := &MockComputeLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockComputeLayer is an autogenerated mock type for the ComputeLayer type
type MockComputeLayer struct {
	mock.Mock
}

type MockComputeLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComputeLayer) EXPECT() *MockComputeLayer_Expecter {
	return &MockComputeLayer_Expecter{mock: &_m.Mock}
}

// ParseAndValidate provides a mock function for the type MockComputeLayer
func (_mock *MockComputeLayer) ParseAndValidate(context1 context.Context, raw string) ([]string, error) {
	ret := _mock.Called(context1, raw)

	if len(ret) == 0 {
		panic("no return value specified for ParseAndValidate")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(context1, raw)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(context1, raw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, raw)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockComputeLayer_ParseAndValidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseAndValidate'
type MockComputeLayer_ParseAndValidate_Call struct {
	*mock.Call
}

// ParseAndValidate is a helper method to define mock.On call
//   - context1 context.Context
//   - raw string
func (_e *MockComputeLayer_Expecter) ParseAndValidate(context1 interface{}, raw interface{}) *MockComputeLayer_ParseAndValidate_Call {
	return &MockComputeLayer_ParseAndValidate_Call{Call: _e.mock.On("ParseAndValidate", context1, raw)}
}

func (_c *MockComputeLayer_ParseAndValidate_Call) Run(run func(context1 context.Context, raw string)) *MockComputeLayer_ParseAndValidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockComputeLayer_ParseAndValidate_Call) Return(strings []string, err error) *MockComputeLayer_ParseAndValidate_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockComputeLayer_ParseAndValidate_Call) RunAndReturn(run func(context1 context.Context, raw string) ([]string, error)) *MockComputeLayer_ParseAndValidate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorageLayer creates a new instance of MockStorageLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageLayer {
	mock := &MockStorageLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorageLayer is an autogenerated mock type for the StorageLayer type
type MockStorageLayer struct {
	mock.Mock
}

type MockStorageLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageLayer) EXPECT() *MockStorageLayer_Expecter {
	return &MockStorageLayer_Expecter{mock: &_m.Mock}
}

// Del provides a mock function for the type MockStorageLayer
func (_mock *MockStorageLayer) Del(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageLayer_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockStorageLayer_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorageLayer_Expecter) Del(ctx interface{}, key interface{}) *MockStorageLayer_Del_Call {
	return &MockStorageLayer_Del_Call{Call: _e.mock.On("Del", ctx, key)}
}

func (_c *MockStorageLayer_Del_Call) Run(run func(ctx context.Context, key string)) *MockStorageLayer_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageLayer_Del_Call) Return(err error) *MockStorageLayer_Del_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageLayer_Del_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockStorageLayer_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockStorageLayer
func (_mock *MockStorageLayer) Get(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageLayer_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStorageLayer_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorageLayer_Expecter) Get(ctx interface{}, key interface{}) *MockStorageLayer_Get_Call {
	return &MockStorageLayer_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockStorageLayer_Get_Call) Run(run func(ctx context.Context, key string)) *MockStorageLayer_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageLayer_Get_Call) Return(s string, err error) *MockStorageLayer_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStorageLayer_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockStorageLayer_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockStorageLayer
func (_mock *MockStorageLayer) Set(ctx context.Context, key string, value string) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageLayer_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockStorageLayer_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *MockStorageLayer_Expecter) Set(ctx interface{}, key interface{}, value interface{}) *MockStorageLayer_Set_Call {
	return &MockStorageLayer_Set_Call{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *MockStorageLayer_Set_Call) Run(run func(ctx context.Context, key string, value string)) *MockStorageLayer_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageLayer_Set_Call) Return(err error) *MockStorageLayer_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageLayer_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value string) error) *MockStorageLayer_Set_Call {
	_c.Call.Return(run)
	return _c
}
