// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage_test

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandStorage creates a new instance of MockCommandStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandStorage {
	mock := &MockCommandStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandStorage is an autogenerated mock type for the CommandStorage type
type MockCommandStorage struct {
	mock.Mock
}

type MockCommandStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandStorage) EXPECT() *MockCommandStorage_Expecter {
	return &MockCommandStorage_Expecter{mock: &_m.Mock}
}

// Del provides a mock function for the type MockCommandStorage
func (_mock *MockCommandStorage) Del(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommandStorage_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockCommandStorage_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCommandStorage_Expecter) Del(ctx interface{}, key interface{}) *MockCommandStorage_Del_Call {
	return &MockCommandStorage_Del_Call{Call: _e.mock.On("Del", ctx, key)}
}

func (_c *MockCommandStorage_Del_Call) Run(run func(ctx context.Context, key string)) *MockCommandStorage_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommandStorage_Del_Call) Return(err error) *MockCommandStorage_Del_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommandStorage_Del_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockCommandStorage_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockCommandStorage
func (_mock *MockCommandStorage) Set(ctx context.Context, key string, value string) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommandStorage_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCommandStorage_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *MockCommandStorage_Expecter) Set(ctx interface{}, key interface{}, value interface{}) *MockCommandStorage_Set_Call {
	return &MockCommandStorage_Set_Call{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *MockCommandStorage_Set_Call) Run(run func(ctx context.Context, key string, value string)) *MockCommandStorage_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCommandStorage_Set_Call) Return(err error) *MockCommandStorage_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommandStorage_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value string) error) *MockCommandStorage_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueryStorage creates a new instance of MockQueryStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryStorage {
	mock := &MockQueryStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryStorage is an autogenerated mock type for the QueryStorage type
type MockQueryStorage struct {
	mock.Mock
}

type MockQueryStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryStorage) EXPECT() *MockQueryStorage_Expecter {
	return &MockQueryStorage_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockQueryStorage
func (_mock *MockQueryStorage) Get(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockQueryStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockQueryStorage_Expecter) Get(ctx interface{}, key interface{}) *MockQueryStorage_Get_Call {
	return &MockQueryStorage_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockQueryStorage_Get_Call) Run(run func(ctx context.Context, key string)) *MockQueryStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueryStorage_Get_Call) Return(s string, err error) *MockQueryStorage_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockQueryStorage_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockQueryStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}
