// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package inmemory_test

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandEngine creates a new instance of MockCommandEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandEngine {
	mock := &MockCommandEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandEngine is an autogenerated mock type for the CommandEngine type
type MockCommandEngine struct {
	mock.Mock
}

type MockCommandEngine_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandEngine) EXPECT() *MockCommandEngine_Expecter {
	return &MockCommandEngine_Expecter{mock: &_m.Mock}
}

// Del provides a mock function for the type MockCommandEngine
func (_mock *MockCommandEngine) Del(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommandEngine_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockCommandEngine_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCommandEngine_Expecter) Del(ctx interface{}, key interface{}) *MockCommandEngine_Del_Call {
	return &MockCommandEngine_Del_Call{Call: _e.mock.On("Del", ctx, key)}
}

func (_c *MockCommandEngine_Del_Call) Run(run func(ctx context.Context, key string)) *MockCommandEngine_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommandEngine_Del_Call) Return(err error) *MockCommandEngine_Del_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommandEngine_Del_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockCommandEngine_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockCommandEngine
func (_mock *MockCommandEngine) Set(ctx context.Context, key string, value string) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommandEngine_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCommandEngine_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *MockCommandEngine_Expecter) Set(ctx interface{}, key interface{}, value interface{}) *MockCommandEngine_Set_Call {
	return &MockCommandEngine_Set_Call{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *MockCommandEngine_Set_Call) Run(run func(ctx context.Context, key string, value string)) *MockCommandEngine_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCommandEngine_Set_Call) Return(err error) *MockCommandEngine_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommandEngine_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value string) error) *MockCommandEngine_Set_Call {
	_c.Call.Return(run)
	return _c
}
