// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tcp_server_test

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRequestHandler creates a new instance of MockRequestHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestHandler {
	mock := &MockRequestHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRequestHandler is an autogenerated mock type for the RequestHandler type
type MockRequestHandler struct {
	mock.Mock
}

type MockRequestHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestHandler) EXPECT() *MockRequestHandler_Expecter {
	return &MockRequestHandler_Expecter{mock: &_m.Mock}
}

// DatabaseHandler provides a mock function for the type MockRequestHandler
func (_mock *MockRequestHandler) DatabaseHandler(ctx context.Context, raw string) (string, error) {
	ret := _mock.Called(ctx, raw)

	if len(ret) == 0 {
		panic("no return value specified for DatabaseHandler")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, raw)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, raw)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, raw)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRequestHandler_DatabaseHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DatabaseHandler'
type MockRequestHandler_DatabaseHandler_Call struct {
	*mock.Call
}

// DatabaseHandler is a helper method to define mock.On call
//   - ctx context.Context
//   - raw string
func (_e *MockRequestHandler_Expecter) DatabaseHandler(ctx interface{}, raw interface{}) *MockRequestHandler_DatabaseHandler_Call {
	return &MockRequestHandler_DatabaseHandler_Call{Call: _e.mock.On("DatabaseHandler", ctx, raw)}
}

func (_c *MockRequestHandler_DatabaseHandler_Call) Run(run func(ctx context.Context, raw string)) *MockRequestHandler_DatabaseHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRequestHandler_DatabaseHandler_Call) Return(s string, err error) *MockRequestHandler_DatabaseHandler_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRequestHandler_DatabaseHandler_Call) RunAndReturn(run func(ctx context.Context, raw string) (string, error)) *MockRequestHandler_DatabaseHandler_Call {
	_c.Call.Return(run)
	return _c
}
