// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package wal_test

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandHashTable creates a new instance of MockCommandHashTable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandHashTable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandHashTable {
	mock := &MockCommandHashTable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandHashTable is an autogenerated mock type for the CommandHashTable type
type MockCommandHashTable struct {
	mock.Mock
}

type MockCommandHashTable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandHashTable) EXPECT() *MockCommandHashTable_Expecter {
	return &MockCommandHashTable_Expecter{mock: &_m.Mock}
}

// Del provides a mock function for the type MockCommandHashTable
func (_mock *MockCommandHashTable) Del(key string) {
	_mock.Called(key)
	return
}

// MockCommandHashTable_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockCommandHashTable_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - key string
func (_e *MockCommandHashTable_Expecter) Del(key interface{}) *MockCommandHashTable_Del_Call {
	return &MockCommandHashTable_Del_Call{Call: _e.mock.On("Del", key)}
}

func (_c *MockCommandHashTable_Del_Call) Run(run func(key string)) *MockCommandHashTable_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommandHashTable_Del_Call) Return() *MockCommandHashTable_Del_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommandHashTable_Del_Call) RunAndReturn(run func(key string)) *MockCommandHashTable_Del_Call {
	_c.Run(run)
	return _c
}

// Set provides a mock function for the type MockCommandHashTable
func (_mock *MockCommandHashTable) Set(key string, value string) {
	_mock.Called(key, value)
	return
}

// MockCommandHashTable_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCommandHashTable_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *MockCommandHashTable_Expecter) Set(key interface{}, value interface{}) *MockCommandHashTable_Set_Call {
	return &MockCommandHashTable_Set_Call{Call: _e.mock.On("Set", key, value)}
}

func (_c *MockCommandHashTable_Set_Call) Run(run func(key string, value string)) *MockCommandHashTable_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommandHashTable_Set_Call) Return() *MockCommandHashTable_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommandHashTable_Set_Call) RunAndReturn(run func(key string, value string)) *MockCommandHashTable_Set_Call {
	_c.Run(run)
	return _c
}

// newMocksegmentRead creates a new instance of mocksegmentRead. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksegmentRead(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksegmentRead {
	mock := &mocksegmentRead{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocksegmentRead is an autogenerated mock type for the segmentRead type
type mocksegmentRead struct {
	mock.Mock
}

type mocksegmentRead_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksegmentRead) EXPECT() *mocksegmentRead_Expecter {
	return &mocksegmentRead_Expecter{mock: &_m.Mock}
}

// GetList provides a mock function for the type mocksegmentRead
func (_mock *mocksegmentRead) GetList(filePath string) ([]string, error) {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(filePath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(filePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksegmentRead_GetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetList'
type mocksegmentRead_GetList_Call struct {
	*mock.Call
}

// GetList is a helper method to define mock.On call
//   - filePath string
func (_e *mocksegmentRead_Expecter) GetList(filePath interface{}) *mocksegmentRead_GetList_Call {
	return &mocksegmentRead_GetList_Call{Call: _e.mock.On("GetList", filePath)}
}

func (_c *mocksegmentRead_GetList_Call) Run(run func(filePath string)) *mocksegmentRead_GetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocksegmentRead_GetList_Call) Return(strings []string, err error) *mocksegmentRead_GetList_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *mocksegmentRead_GetList_Call) RunAndReturn(run func(filePath string) ([]string, error)) *mocksegmentRead_GetList_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type mocksegmentRead
func (_mock *mocksegmentRead) Read(filePath string) ([]byte, error) {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(filePath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(filePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksegmentRead_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type mocksegmentRead_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - filePath string
func (_e *mocksegmentRead_Expecter) Read(filePath interface{}) *mocksegmentRead_Read_Call {
	return &mocksegmentRead_Read_Call{Call: _e.mock.On("Read", filePath)}
}

func (_c *mocksegmentRead_Read_Call) Run(run func(filePath string)) *mocksegmentRead_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocksegmentRead_Read_Call) Return(bytes []byte, err error) *mocksegmentRead_Read_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *mocksegmentRead_Read_Call) RunAndReturn(run func(filePath string) ([]byte, error)) *mocksegmentRead_Read_Call {
	_c.Call.Return(run)
	return _c
}

// newMocksegmentWrite creates a new instance of mocksegmentWrite. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksegmentWrite(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksegmentWrite {
	mock := &mocksegmentWrite{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocksegmentWrite is an autogenerated mock type for the segmentWrite type
type mocksegmentWrite struct {
	mock.Mock
}

type mocksegmentWrite_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksegmentWrite) EXPECT() *mocksegmentWrite_Expecter {
	return &mocksegmentWrite_Expecter{mock: &_m.Mock}
}

// SetFile provides a mock function for the type mocksegmentWrite
func (_mock *mocksegmentWrite) SetFile(file *os.File) {
	_mock.Called(file)
	return
}

// mocksegmentWrite_SetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFile'
type mocksegmentWrite_SetFile_Call struct {
	*mock.Call
}

// SetFile is a helper method to define mock.On call
//   - file *os.File
func (_e *mocksegmentWrite_Expecter) SetFile(file interface{}) *mocksegmentWrite_SetFile_Call {
	return &mocksegmentWrite_SetFile_Call{Call: _e.mock.On("SetFile", file)}
}

func (_c *mocksegmentWrite_SetFile_Call) Run(run func(file *os.File)) *mocksegmentWrite_SetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *os.File
		if args[0] != nil {
			arg0 = args[0].(*os.File)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocksegmentWrite_SetFile_Call) Return() *mocksegmentWrite_SetFile_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocksegmentWrite_SetFile_Call) RunAndReturn(run func(file *os.File)) *mocksegmentWrite_SetFile_Call {
	_c.Run(run)
	return _c
}

// Write provides a mock function for the type mocksegmentWrite
func (_mock *mocksegmentWrite) Write(data []byte) error {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mocksegmentWrite_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type mocksegmentWrite_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - data []byte
func (_e *mocksegmentWrite_Expecter) Write(data interface{}) *mocksegmentWrite_Write_Call {
	return &mocksegmentWrite_Write_Call{Call: _e.mock.On("Write", data)}
}

func (_c *mocksegmentWrite_Write_Call) Run(run func(data []byte)) *mocksegmentWrite_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocksegmentWrite_Write_Call) Return(err error) *mocksegmentWrite_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mocksegmentWrite_Write_Call) RunAndReturn(run func(data []byte) error) *mocksegmentWrite_Write_Call {
	_c.Call.Return(run)
	return _c
}
